# Generated by Django 4.2.13 on 2024-06-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabelog", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="member_type",
            field=models.CharField(
                blank=True,
                choices=[("1", "無料"), ("2", "有料")],
                max_length=2,
                null=True,
                verbose_name="会員種別",
            ),
        ),
    ]
