# Generated by Django 4.2.13 on 2024-06-05 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tabelog", "0004_alter_user_member_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=55, verbose_name="カテゴリ名")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
            ],
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("store_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=264, verbose_name="店舗名")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="store_images/",
                        verbose_name="画像",
                    ),
                ),
                ("description", models.TextField(verbose_name="説明")),
                ("lowest_price", models.IntegerField(verbose_name="価格帯(下限)")),
                ("highest_price", models.IntegerField(verbose_name="価格帯(上限)")),
                ("opening_time", models.TimeField(verbose_name="営業時間(開店)")),
                ("closing_time", models.TimeField(verbose_name="営業時間(閉店)")),
                ("postal_code", models.CharField(max_length=11, verbose_name="郵便番号")),
                ("address", models.CharField(max_length=264, verbose_name="住所")),
                ("phone_number", models.CharField(max_length=55, verbose_name="電話番号")),
                ("seating_capacity", models.IntegerField(verbose_name="座席数")),
                (
                    "regular_holiday",
                    models.CharField(max_length=55, verbose_name="定休日"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="登録日"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="tabelog.category",
                    ),
                ),
            ],
        ),
    ]
