# Generated by Django 4.2.13 on 2024-06-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0009_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('1', '無料'), ('2', '有料')], default='1', max_length=2, verbose_name='会員種別'),
        ),
    ]
