# Generated by Django 4.2.13 on 2024-06-19 04:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tabelog", "0010_alter_user_member_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="画像"
            ),
        ),
    ]
