# Generated by Django 4.2.13 on 2024-06-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tabelog", "0011_alter_store_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="store_images/", verbose_name="画像"
            ),
        ),
    ]
